const Joi = require('joi');

const stripHtml = (value, helpers) => {
  if (typeof value === 'string') return value.replace(/<[^>]*>/g, '');
  return value;
};
const hf = () => Joi.string().custom(stripHtml, 'HTML strip');

const hrmsSchemas = {
  createDepartment: Joi.object({
    name: hf().min(2).max(100).required(),
    description: hf().optional().allow(''),
  }),
  updateDepartment: Joi.object({
    name: hf().min(2).max(100).optional(),
    description: hf().optional().allow(''),
    isActive: Joi.boolean().optional(),
  }),

  createPosition: Joi.object({
    title: hf().min(2).max(100).required(),
    departmentId: Joi.number().integer().positive().required(),
    roleSlug: Joi.string().valid('admin', 'hr', 'manager', 'cashier', 'inventory_staff', 'employee').optional().default('employee'),
    minSalary: Joi.number().min(0).optional().default(0),
    maxSalary: Joi.number().min(Joi.ref('minSalary')).optional().default(0),
    description: hf().optional().allow(''),
  }),
  updatePosition: Joi.object({
    title: hf().min(2).max(100).optional(),
    departmentId: Joi.number().integer().positive().optional(),
    roleSlug: Joi.string().valid('admin', 'hr', 'manager', 'cashier', 'inventory_staff', 'employee').optional(),
    minSalary: Joi.number().min(0).optional(),
    maxSalary: Joi.number().min(Joi.ref('minSalary')).optional(),
    description: hf().optional().allow(''),
    isActive: Joi.boolean().optional(),
  }),

  createEmployee: Joi.object({
    firstName: hf().min(2).max(100).pattern(/^[\p{L}\s'.,-]+$/u).required(),
    middleName: hf().max(100).optional().allow(''),
    lastName: hf().min(2).max(100).pattern(/^[\p{L}\s'.,-]+$/u).required(),
    email: Joi.string().email().max(150).required(),
    phone: Joi.string().min(7).max(20).optional().allow(''),
    civilStatus: Joi.string().valid('single', 'married', 'widowed', 'separated', 'divorced').optional(),
    nationality: hf().max(50).optional().allow(''),
    address: hf().optional().allow(''),
    gender: Joi.string().valid('male', 'female', 'other').optional(),
    birthDate: Joi.date().optional().allow(null),
    hireDate: Joi.date().required(),
    departmentId: Joi.number().integer().positive().required(),
    positionId: Joi.number().integer().positive().required(),
    reportsToId: Joi.number().integer().positive().optional().allow(null),
    salary: Joi.number().min(0).required(),
    employmentType: Joi.string().valid('full-time', 'part-time', 'contract').optional().default('full-time'),
    paymentFrequency: Joi.string().valid('monthly', 'semi-monthly').optional().default('monthly'),
    tinNumber: hf().max(20).optional().allow(''),
    sssNumber: hf().max(20).optional().allow(''),
    philHealthNumber: hf().max(20).optional().allow(''),
    pagIbigNumber: hf().max(20).optional().allow(''),
    bankName: hf().max(100).optional().allow(''),
    bankAccountNumber: hf().max(50).pattern(/^\d*$/).optional().allow(''),
    emergencyContactName: hf().max(150).optional().allow(''),
    emergencyContactPhone: hf().max(20).optional().allow(''),
    emergencyContactRelation: hf().max(50).optional().allow(''),
    educationLevel: hf().max(100).optional().allow(''),
    status: Joi.string().valid('active', 'inactive', 'on-leave').optional().default('active'),
  }),
  updateEmployee: Joi.object({
    firstName: hf().min(2).max(100).pattern(/^[\p{L}\s'.,-]+$/u).optional(),
    middleName: hf().max(100).optional().allow(''),
    lastName: hf().min(2).max(100).pattern(/^[\p{L}\s'.,-]+$/u).optional(),
    email: Joi.string().email().max(150).optional(),
    phone: Joi.string().min(7).max(20).optional().allow(''),
    civilStatus: Joi.string().valid('single', 'married', 'widowed', 'separated', 'divorced').optional(),
    nationality: hf().max(50).optional().allow(''),
    address: hf().optional().allow(''),
    gender: Joi.string().valid('male', 'female', 'other').optional(),
    birthDate: Joi.date().optional().allow(null),
    hireDate: Joi.date().optional(),
    departmentId: Joi.number().integer().positive().optional(),
    positionId: Joi.number().integer().positive().optional(),
    reportsToId: Joi.number().integer().positive().optional().allow(null),
    salary: Joi.number().min(0).optional(),
    employmentType: Joi.string().valid('full-time', 'part-time', 'contract').optional(),
    paymentFrequency: Joi.string().valid('monthly', 'semi-monthly').optional(),
    tinNumber: hf().max(20).optional().allow(''),
    sssNumber: hf().max(20).optional().allow(''),
    philHealthNumber: hf().max(20).optional().allow(''),
    pagIbigNumber: hf().max(20).optional().allow(''),
    bankName: hf().max(100).optional().allow(''),
    bankAccountNumber: hf().max(50).pattern(/^\d*$/).optional().allow(''),
    emergencyContactName: hf().max(150).optional().allow(''),
    emergencyContactPhone: hf().max(20).optional().allow(''),
    emergencyContactRelation: hf().max(50).optional().allow(''),
    educationLevel: hf().max(100).optional().allow(''),
    status: Joi.string().valid('active', 'inactive', 'on-leave', 'pending').optional(),
    terminationType: Joi.string().valid('resignation', 'for-cause', 'end-of-contract', 'retrenchment', 'retirement').optional(),
    terminationDate: Joi.date().optional().allow(null),
  }),

  clockIn: Joi.object({
    employeeId: Joi.number().integer().positive().optional(),
    latitude: Joi.number().min(-90).max(90).optional().allow(null),
    longitude: Joi.number().min(-180).max(180).optional().allow(null),
    // Set when the client could not resolve a position, so the server knows to
    // demand one if the branch enforces a geofence.
    checkGeofence: Joi.boolean().optional(),
    notes: hf().optional().allow(''),
  }),
  clockOut: Joi.object({
    employeeId: Joi.number().integer().positive().optional(),
    notes: hf().optional().allow(''),
  }),
  createAttendance: Joi.object({
    employeeId: Joi.number().integer().positive().required(),
    date: Joi.date().required(),
    clockIn: Joi.date().optional().allow(null),
    clockOut: Joi.date().optional().allow(null),
    status: Joi.string().valid('present', 'absent', 'late', 'undertime', 'half-day').optional().default('present'),
    overtime: Joi.number().min(0).optional().default(0),
    holidayType: Joi.string().valid('none', 'regular', 'special').optional().default('none'),
    isRestDay: Joi.boolean().optional().default(false),
    isOvertimeApproved: Joi.boolean().optional().default(false),
    notes: hf().optional().allow(''),
  }),
  updateAttendance: Joi.object({
    clockIn: Joi.date().optional().allow(null),
    clockOut: Joi.date().optional().allow(null),
    status: Joi.string().valid('present', 'absent', 'late', 'undertime', 'half-day', 'on-leave').optional(),
    overtime: Joi.number().min(0).optional(),
    holidayType: Joi.string().valid('none', 'regular', 'special').optional(),
    isRestDay: Joi.boolean().optional(),
    isOvertimeApproved: Joi.boolean().optional(),
    notes: hf().optional().allow(''),
  }),

  createSchedule: Joi.object({
    name: hf().min(2).max(100).required(),
    startTime: Joi.string().pattern(/^([01]\d|2[0-3]):[0-5]\d$/).required(),
    endTime: Joi.string().pattern(/^([01]\d|2[0-3]):[0-5]\d$/).required(),
    daysOfWeek: Joi.alternatives().try(Joi.array().items(Joi.number().integer().min(0).max(6)), Joi.string()).optional().default('1,2,3,4,5'),
    breakMinutes: Joi.number().integer().min(0).max(240).optional().default(60),
    description: hf().optional().allow(''),
  }),
  updateSchedule: Joi.object({
    name: hf().min(2).max(100).optional(),
    startTime: Joi.string().pattern(/^([01]\d|2[0-3]):[0-5]\d$/).optional(),
    endTime: Joi.string().pattern(/^([01]\d|2[0-3]):[0-5]\d$/).optional(),
    daysOfWeek: Joi.alternatives().try(Joi.array().items(Joi.number().integer().min(0).max(6)), Joi.string()).optional(),
    breakMinutes: Joi.number().integer().min(0).max(240).optional(),
    description: hf().optional().allow(''),
    isActive: Joi.boolean().optional(),
  }),
  assignShift: Joi.object({
    employeeId: Joi.number().integer().positive().required(),
    scheduleId: Joi.number().integer().positive().required(),
    date: Joi.date().optional(),
  }),

  createJobPosting: Joi.object({
    title: hf().min(2).max(150).required(),
    departmentId: Joi.number().integer().positive().required(),
    positionId: Joi.number().integer().positive().required(),
    scheduleId: Joi.number().integer().positive().optional().allow(null),
    description: hf().min(10).required(),
    requirements: hf().optional().allow(''),
    salaryMin: Joi.number().min(0).optional().allow(null),
    salaryMax: Joi.number().min(0).optional().allow(null),
    employmentType: Joi.string().valid('full-time', 'part-time', 'contract').optional().default('full-time'),
    paymentFrequency: Joi.string().valid('monthly', 'semi-monthly').optional().default('monthly'),
    openings: Joi.number().integer().min(1).max(100).optional().default(1),
    closingDate: Joi.date().min('now').optional().allow(null).messages({ 'date.min': 'Closing date cannot be in the past' }),
    location: hf().max(100).optional().allow(''),
  }),
  updateJobPosting: Joi.object({
    title: hf().min(2).max(150).optional(),
    departmentId: Joi.number().integer().positive().optional(),
    positionId: Joi.number().integer().positive().optional().allow(null),
    scheduleId: Joi.number().integer().positive().optional().allow(null),
    description: hf().min(10).optional(),
    requirements: hf().optional().allow(''),
    salaryMin: Joi.number().min(0).optional().allow(null),
    salaryMax: Joi.number().min(0).optional().allow(null),
    employmentType: Joi.string().valid('full-time', 'part-time', 'contract').optional(),
    paymentFrequency: Joi.string().valid('monthly', 'semi-monthly').optional(),
    openings: Joi.number().integer().min(1).max(100).optional(),
    closingDate: Joi.date().min('now').optional().allow(null).messages({ 'date.min': 'Closing date cannot be in the past' }),
    location: hf().max(100).optional().allow(''),
    status: Joi.string().valid('open', 'closed', 'filled').optional(),
  }),
  applyJob: Joi.object({
    jobId: Joi.number().integer().positive().required(),
    firstName: hf().min(2).max(100).pattern(/^[\p{L}\s'.,-]+$/u).required(),
    middleName: hf().max(100).optional().allow(''),
    lastName: hf().min(2).max(100).pattern(/^[\p{L}\s'.,-]+$/u).required(),
    email: Joi.string().email().max(150).required(),
    phone: Joi.string().min(7).max(20).optional().allow(''),
    coverLetter: hf().optional().allow(''),
  }),
  scheduleInterview: Joi.object({
    applicationId: Joi.number().integer().positive().required(),
    type: Joi.string().valid('initial', 'final').required(),
    scheduledDate: Joi.date().min('now').required().messages({ 'date.min': 'Interview date cannot be in the past' }),
    scheduledTime: Joi.string().required(),
    interviewer: hf().min(2).max(150).required(),
    location: hf().optional().allow(''),
    latitude: Joi.number().optional().allow(null, ''),
    longitude: Joi.number().optional().allow(null, ''),
    notes: hf().optional().allow(''),
  }),

  createContract: Joi.object({
    employeeId: Joi.number().integer().positive().required(),
    contractType: Joi.string().valid('regular', 'probationary', 'contract', 'deployment', 'project').required(),
    paymentFrequency: Joi.string().valid('monthly', 'semi-monthly').optional().default('monthly'),
    startDate: Joi.date().min('now').required(),
    endDate: Joi.date().min(Joi.ref('startDate')).optional().allow(null),
    salary: Joi.number().min(0).optional().allow(null),
    terms: hf().optional().allow(''),
    notes: hf().optional().allow(''),
  }),

  createLeave: Joi.object({
    employeeId: Joi.number().integer().positive().optional(),
    leaveType: Joi.string().valid('sick', 'vacation', 'personal', 'maternity', 'paternity', 'bereavement', 'other').required(),
    startDate: Joi.date().required(),
    endDate: Joi.date().min(Joi.ref('startDate')).required(),
    reason: hf().min(5).required(),
    isPaid: Joi.boolean().optional().default(true),
  }),

  generatePayroll: Joi.object({
    month: Joi.number().integer().min(1).max(12).required(),
    year: Joi.number().integer().min(2020).max(2030).required(),
    periodType: Joi.string().valid('monthly', 'semi-monthly').optional().default('monthly'),
    half: Joi.number().integer().valid(1, 2).optional(),
    departmentId: Joi.number().integer().positive().optional().allow(null),
    bonuses: Joi.object().pattern(/^[0-9]+$/, Joi.number().min(0)).optional(),
  }),

  updateContract: Joi.object({
    contractType: Joi.string().valid('regular', 'probationary', 'contract', 'deployment', 'project').optional(),
    paymentFrequency: Joi.string().valid('monthly', 'semi-monthly').optional(),
    startDate: Joi.date().optional(),
    endDate: Joi.date().optional().allow(null),
    salary: Joi.number().min(0).optional().allow(null),
    terms: hf().optional().allow(''),
    notes: hf().optional().allow(''),
  }),
  renewContract: Joi.object({
    contractType: Joi.string().valid('regular', 'probationary', 'contract', 'deployment', 'project').required(),
    paymentFrequency: Joi.string().valid('monthly', 'semi-monthly').optional().default('monthly'),
    startDate: Joi.date().required(),
    endDate: Joi.date().min(Joi.ref('startDate')).optional().allow(null),
    salary: Joi.number().min(0).optional().allow(null),
    terms: hf().optional().allow(''),
    notes: hf().optional().allow(''),
  }),
  terminateEmployee: Joi.object({
    terminationType: Joi.string().valid('resignation', 'for-cause', 'end-of-contract', 'retrenchment', 'retirement').optional().default('end-of-contract'),
    terminationDate: Joi.date().optional(),
  }),
  updateInterview: Joi.object({
    scheduledDate: Joi.date().optional(),
    scheduledTime: Joi.string().optional(),
    interviewer: hf().min(2).max(150).optional(),
    location: hf().optional().allow(''),
    latitude: Joi.number().optional().allow(null, ''),
    longitude: Joi.number().optional().allow(null, ''),
    notes: hf().optional().allow(''),
  }),
  updateInterviewResult: Joi.object({
    result: Joi.string().valid('pass', 'fail', 'cancelled').required(),
    feedback: hf().optional().allow(''),
  }),
  updateApplicationStatus: Joi.object({
    status: Joi.string().valid('pending', 'reviewed', 'initial-interview', 'final-interview', 'accepted', 'rejected', 'hired').required(),
    notes: hf().optional().allow(''),
  }),
  hrReviewLeave: Joi.object({
    remarks: hf().optional().allow(''),
  }),
  adminRejectLeave: Joi.object({
    remarks: hf().min(3).required(),
  }),
  updateProfile: Joi.object({
    phone: Joi.string().min(7).max(20).optional().allow(''),
    address: hf().optional().allow(''),
    emergencyContactName: hf().max(150).optional().allow(''),
    emergencyContactPhone: hf().max(20).optional().allow(''),
    emergencyContactRelation: hf().max(50).optional().allow(''),
    bankName: hf().max(100).optional().allow(''),
    bankAccountNumber: hf().max(50).pattern(/^\d*$/).optional().allow(''),
  }),
};

module.exports = hrmsSchemas;
